//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace museumProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class gift
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<double> cost { get; set; }
        public string material { get; set; }
        public string photo { get; set; }
        public HttpPostedFileBase photo_file { get; set; }
        public Nullable<int> houseId { get; set; }
        public Nullable<bool> available { get; set; }
    
        public virtual house house { get; set; }
    }
}
