//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace museumProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class house
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public house()
        {
            this.gifts = new HashSet<gift>();
            this.houses1 = new HashSet<house>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string photo { get; set; }
        public string governorate { get; set; }
        public string address { get; set; }
        public Nullable<decimal> Lattitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> placeId { get; set; }
        public string description { get; set; }
        public HttpPostedFileBase photo_file { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gift> gifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<house> houses1 { get; set; }
        public virtual house house1 { get; set; }
        public virtual place place { get; set; }
    }
}
