//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace museumProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class menument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menument()
        {
            this.menument_images = new HashSet<menument_images>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string voice_note { get; set; }
        public string QR_image { get; set; }
        public Nullable<int> no_of_scans { get; set; }
        public Nullable<int> place_id { get; set; }
        public HttpPostedFileBase Logo_file { get; set; }
        public HttpPostedFileBase Audio_file { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menument_images> menument_images { get; set; }
        public virtual place place { get; set; }
    }
}
