//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace museumProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class place_images
    {
        public int id { get; set; }
        public Nullable<int> place_id { get; set; }
        public string image { get; set; }
        public string altr { get; set; }
        public HttpPostedFileBase image_file { get; set; }
        public virtual place place { get; set; }
    }
}
