//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace museumProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class places_cat
    {
        public int place_id { get; set; }
        public int cat_id { get; set; }
        public Nullable<int> rank { get; set; }
    
        public virtual catogery catogery { get; set; }
        public virtual place place { get; set; }
    }
}
